language: php

php:
  - 5.4
  - 5.5
  - 5.6
#  - hhvm
  - 7.0

env:
  - DB=sqlite
  - DB=mysql
#  - DB=postgres

before_script :
  - composer install
  - mysql -e 'create database active_record_test;'
  - mysql -e "use mysql; SET PASSWORD FOR 'travis'@'localhost' = PASSWORD('travis'); FLUSH PRIVILEGES;"

after_script:
  - CODECLIMATE_REPO_TOKEN="699713275755baa3e2596e1f4eb5d399728b0539bdc43b82543ff893ddaf816f" vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

script:
  - ./vendor/bin/phpcs --warning-severity=6 --standard=PSR2 *.php src tests
  - phpunit

notifications:
  email:
    - matthew@baggett.me
  slack: thruio:m7cGYXmdz261AkGDfiRVBHmY
