language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

addons:
  code_climate:
    repo_token: 699713275755baa3e2596e1f4eb5d399728b0539bdc43b82543ff893ddaf816f

before_script :
  - composer install
  - mysql -e 'create database active_record_test;'

after_script:
  - vendor/bin/test-reporter

script: phpunit --configuration phpunit.xml --coverage-text

notifications:
  email:
    - matthew@baggett.me